author:
  name   : "Milton Silas"
  avatar : "/assets/images/milton-profile.jpg"
  bio    : "Cybersecurity Analyst • Red Team Specialist • Cisco Instructor"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:miltonsilas564@gmail.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Milton511"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/milton-silas-736a852b8"
include:
  - labs.html
